image:
  App:
    repository: docker.io/trabelsihammamimanel/pfe-project
    Tag: app-af3dec45
  
  
replicas:
  App: 2

hpa:
  App:
    minReplicas: 1
    maxReplicas: 3
  

imagePullSecrets:
  - name: regcred
  

