image:
  App:
    repository: docker.io/trabelsihammamimanel/pfe-project
    tag: app-v6

replicas:
  App: 2

hpa:
  App:
    minReplicas: 1
    maxReplicas: 3

imagePullSecrets:
  - name: regcred

service:
  type: NodePort
imagePullSecretData: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImRISmhZbVZzYzJsb1lXMXRZVzFwYldGdVpXdzZaR05yY2w5d1lYUmZPVU5YTTNod1pXcEtRblZtUVRCeE1ITnlZVXhuVUU4MU1YcHIiCiAgICB9CiAgfQp9Cg==
