apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-lrs
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
