apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJheGlhMjAyNSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfXzVPeW14aVkyMmZmQk0wYVhOZVBodW5fN0NvIiwiZW1haWwiOiJoaWJhYmVuamF6aWE3MzJAZ21haWwuY29tIiwiYXV0aCI6IllYaHBZVEl3TWpVNlpHTnJjbDl3WVhSZlh6VlBlVzE0YVZreU1tWm1RazB3WVZoT1pWQm9kVzVmTjBOdiJ9fX0=