apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
      - name: app
        image: "{{ .Values.image.App.repository }}:{{ .Values.image.App.Tag }}"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "run.py"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_CONFIG
          value: "development"
        
        
      
        
        


